[package]
name = "cli"
version = "0.1.0"
authors = ["Ruan Pearce-Authers <ruanpa@outlook.com>"]
edition = "2018"

[[bin]]
name = "qry"
path = "src/main.rs"

[dependencies]
qry = { path = "../qry" }
rustyline = "6.1.2"
