[package]
name = "qry-web"
version = "0.1.0"
authors = ["Ruan Pearce-Authers <ruanpa@outlook.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
qry = { path = "../qry" }
wasm-bindgen = "0.2.63"
