name: Build

on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - macos-10.15
        - windows-2019
        rust:
        - nightly-2020-05-14
        profile:
        - dev
        - release

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: Prep build dir
      run: |
        mkdir build

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -Z unstable-options --profile ${{ matrix.profile }} --out-dir=build

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test 
        args: -Z unstable-options --profile ${{ matrix.profile }}

    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}-${{ matrix.rust }}-${{ matrix.profile }}-qry
        path: build/
