name: Build

on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - macos-10.15
        - windows-2019
        profile:
        - dev
        - release

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1

    - name: Prep build dir
      run: |
        mkdir build

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -Z unstable-options --profile ${{ matrix.profile }} --out-dir=build

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test 
        args: -Z unstable-options --profile ${{ matrix.profile }}

    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: qry-${{ matrix.os }}-${{ matrix.profile }}
        path: build/

  build-wasm:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1

    - name: Install wasm-pack
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build wasm
      run: |
        wasm-pack build qry-web

    - name: Upload wasm build
      uses: actions/upload-artifact@v1
      with:
        name: qry-wasm
        path: qry-web/pkg/
